name: CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  packages: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v6

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: "25"
          cache: "gradle"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Configure GitHub Packages credentials
        run: |
          mkdir -p ~/.gradle
          {
            echo "github.user=${{ github.actor }}"
            echo "github.token=${{ secrets.GITHUB_TOKEN }}"
          } > ~/.gradle/gradle.properties

      - name: Build
        run: ./gradlew build --exclude-task test

      - name: Test
        run: ./gradlew test